# Live Parquet Batch Inspector (Extractor v8 format)
Inspect extraction checkpoints from `batch_results/results_batch_*` as they are being generated by `spotify_extractor_v8.ipynb`.

This notebook supports both `.parquet` and `.pkl` checkpoints (same behavior as extractor v8).

In [1]:
from pathlib import Path
from datetime import datetime
import re
import time

import polars as pl
import pandas as pd

# Must match spotify_extractor_v8.ipynb
BATCH_DIR = Path('batch_results')
PATTERN = 'results_batch_*'

print(f'Watching batch directory: {BATCH_DIR.resolve()}')

Watching batch directory: /home/build/martin/spotify_v2/batch_results

In [2]:
def list_checkpoint_files(batch_dir: Path = BATCH_DIR):
    files = sorted(
        [p for p in batch_dir.glob(PATTERN) if p.suffix in {'.parquet', '.pkl'}],
        key=lambda p: p.name
    )
    return files


def parse_batch_index(path: Path) -> int | None:
    m = re.search(r'results_batch_(\d+)', path.name)
    return int(m.group(1)) if m else None


checkpoint_files = list_checkpoint_files()
print(f'Found {len(checkpoint_files)} checkpoint files.')
for p in checkpoint_files[-10:]:
    print(' -', p.name)

Found 411 checkpoint files.
 - results_batch_00402.parquet
 - results_batch_00403.parquet
 - results_batch_00404.parquet
 - results_batch_00405.parquet
 - results_batch_00406.parquet
 - results_batch_00407.parquet
 - results_batch_00408.parquet
 - results_batch_00409.parquet
 - results_batch_00410.parquet
 - results_batch_00411.parquet

In [3]:
if checkpoint_files:
    summary_rows = []
    for p in checkpoint_files:
        stat = p.stat()
        summary_rows.append({
            'batch_index': parse_batch_index(p),
            'file': p.name,
            'format': p.suffix.replace('.', ''),
            'size_mb': round(stat.st_size / (1024 * 1024), 3),
            'modified_at': datetime.fromtimestamp(stat.st_mtime).strftime('%Y-%m-%d %H:%M:%S'),
        })

    files_df = pl.DataFrame(summary_rows).sort('batch_index')
    display(files_df)
else:
    files_df = pl.DataFrame()
    print('No checkpoint files found yet.')

files_df

shape: (411, 5)
┌─────────────┬─────────────────────────────┬─────────┬─────────┬─────────────────────┐
│ batch_index ┆ file                        ┆ format  ┆ size_mb ┆ modified_at         │
│ ---         ┆ ---                         ┆ ---     ┆ ---     ┆ ---                 │
│ i64         ┆ str                         ┆ str     ┆ f64     ┆ str                 │
╞═════════════╪═════════════════════════════╪═════════╪═════════╪═════════════════════╡
│ 1           ┆ results_batch_00001.parquet ┆ parquet ┆ 2.504   ┆ 2026-03-15 10:58:59 │
│ 2           ┆ results_batch_00002.parquet ┆ parquet ┆ 4.934   ┆ 2026-03-15 11:07:50 │
│ 3           ┆ results_batch_00003.parquet ┆ parquet ┆ 3.294   ┆ 2026-03-15 11:13:12 │
│ 4           ┆ results_batch_00004.parquet ┆ parquet ┆ 6.887   ┆ 2026-03-15 11:22:07 │
│ 5           ┆ results_batch_00005.parquet ┆ parquet ┆ 4.626   ┆ 2026-03-15 11:28:12 │
│ …           ┆ …                           ┆ …       ┆ …       ┆ …                   │
│ 407         ┆ results_batch_00407.parquet ┆ parquet ┆ 0.719   ┆ 2026-03-17 06:10:14 │
│ 408         ┆ results_batch_00408.parquet ┆ parquet ┆ 0.74    ┆ 2026-03-17 06:15:13 │
│ 409         ┆ results_batch_00409.parquet ┆ parquet ┆ 0.757   ┆ 2026-03-17 06:19:58 │
│ 410         ┆ results_batch_00410.parquet ┆ parquet ┆ 0.792   ┆ 2026-03-17 06:24:38 │
│ 411         ┆ results_batch_00411.parquet ┆ parquet ┆ 0.759   ┆ 2026-03-17 06:29:29 │
└─────────────┴─────────────────────────────┴─────────┴─────────┴─────────────────────┘

shape: (411, 5)
┌─────────────┬─────────────────────────────┬─────────┬─────────┬─────────────────────┐
│ batch_index ┆ file                        ┆ format  ┆ size_mb ┆ modified_at         │
│ ---         ┆ ---                         ┆ ---     ┆ ---     ┆ ---                 │
│ i64         ┆ str                         ┆ str     ┆ f64     ┆ str                 │
╞═════════════╪═════════════════════════════╪═════════╪═════════╪═════════════════════╡
│ 1           ┆ results_batch_00001.parquet ┆ parquet ┆ 2.504   ┆ 2026-03-15 10:58:59 │
│ 2           ┆ results_batch_00002.parquet ┆ parquet ┆ 4.934   ┆ 2026-03-15 11:07:50 │
│ 3           ┆ results_batch_00003.parquet ┆ parquet ┆ 3.294   ┆ 2026-03-15 11:13:12 │
│ 4           ┆ results_batch_00004.parquet ┆ parquet ┆ 6.887   ┆ 2026-03-15 11:22:07 │
│ 5           ┆ results_batch_00005.parquet ┆ parquet ┆ 4.626   ┆ 2026-03-15 11:28:12 │
│ …           ┆ …                           ┆ …       ┆ …       ┆ …                   │
│ 407         ┆ results_batch_00407.parquet ┆ parquet ┆ 0.719   ┆ 2026-03-17 06:10:14 │
│ 408         ┆ results_batch_00408.parquet ┆ parquet ┆ 0.74    ┆ 2026-03-17 06:15:13 │
│ 409         ┆ results_batch_00409.parquet ┆ parquet ┆ 0.757   ┆ 2026-03-17 06:19:58 │
│ 410         ┆ results_batch_00410.parquet ┆ parquet ┆ 0.792   ┆ 2026-03-17 06:24:38 │
│ 411         ┆ results_batch_00411.parquet ┆ parquet ┆ 0.759   ┆ 2026-03-17 06:29:29 │
└─────────────┴─────────────────────────────┴─────────┴─────────┴─────────────────────┘

In [4]:
def read_checkpoint(path: Path) -> pl.DataFrame:
    if path.suffix == '.parquet':
        return pl.read_parquet(path)
    if path.suffix == '.pkl':
        return pl.from_pandas(pd.read_pickle(path))
    return pl.DataFrame()


def load_checkpoints(files: list[Path], latest_n: int | None = None) -> pl.DataFrame:
    use_files = files[-latest_n:] if latest_n else files
    frames = []

    for p in use_files:
        try:
            df_part = read_checkpoint(p).with_columns(pl.lit(p.name).alias('_source_file'))
            frames.append(df_part)
        except Exception as e:
            print(f'Skipping unreadable file {p.name}: {e}')

    if not frames:
        return pl.DataFrame()

    return pl.concat(frames, how='diagonal_relaxed')


# Set latest_n=None to load everything, or an int (e.g. 5) for quicker live checks
latest_n = None
results_df = load_checkpoints(checkpoint_files, latest_n=latest_n)

print(f'Loaded rows: {results_df.height:,}')
print(f'Columns: {results_df.width}')
display(results_df.head(10))

Loaded rows: 411,000
Columns: 20

shape: (10, 20)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ track_id  ┆ original_ ┆ original_ ┆ id        ┆ … ┆ metadata_ ┆ lyrics    ┆ lyrics_st ┆ _source_ │
│ ---       ┆ name      ┆ artist    ┆ ---       ┆   ┆ status    ┆ ---       ┆ atus      ┆ file     │
│ str       ┆ ---       ┆ ---       ┆ str       ┆   ┆ ---       ┆ str       ┆ ---       ┆ ---      │
│           ┆ str       ┆ str       ┆           ┆   ┆ str       ┆           ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1IZc5f9ul ┆ Kingdom   ┆ The Civil ┆ 1IZc5f9ul ┆ … ┆ ok        ┆ Run, run, ┆ ok_lrclib ┆ results_ │
│ w7Ge2eOpQ ┆ Come      ┆ Wars      ┆ w7Ge2eOpQ ┆   ┆           ┆ run away  ┆           ┆ batch_00 │
│ H7w6      ┆           ┆           ┆ H7w6      ┆   ┆           ┆ Buy       ┆           ┆ 001.parq │
│           ┆           ┆           ┆           ┆   ┆           ┆ yoursel…  ┆           ┆ uet      │
│ 53QF56cjZ ┆ I Won't   ┆ Jason     ┆ 53QF56cjZ ┆ … ┆ ok        ┆ When I    ┆ ok_lrclib ┆ results_ │
│ A9RTuuMZD ┆ Give Up   ┆ Mraz      ┆ A9RTuuMZD ┆   ┆           ┆ look into ┆           ┆ batch_00 │
│ rSA6      ┆           ┆           ┆ rSA6      ┆   ┆           ┆ your eyes ┆           ┆ 001.parq │
│           ┆           ┆           ┆           ┆   ┆           ┆ It'…      ┆           ┆ uet      │
│ 7j6t0kr66 ┆ Watching  ┆ Eric Hutc ┆ 7j6t0kr66 ┆ … ┆ ok        ┆ I love    ┆ ok_lrclib ┆ results_ │
│ wFLkBjjKx ┆ You Watch ┆ hinson    ┆ wFLkBjjKx ┆   ┆           ┆ you from  ┆           ┆ batch_00 │
│ h5FJ      ┆ Him       ┆           ┆ h5FJ      ┆   ┆           ┆ the       ┆           ┆ 001.parq │
│           ┆           ┆           ┆           ┆   ┆           ┆ bottom of ┆           ┆ uet      │
│           ┆           ┆           ┆           ┆   ┆           ┆ …         ┆           ┆          │
│ 3Y6BuzQCg ┆ Dancing   ┆ Green     ┆ 3Y6BuzQCg ┆ … ┆ ok        ┆ Put on    ┆ ok_lrclib ┆ results_ │
│ 9p4yH347N ┆ Shoes     ┆ River     ┆ 9p4yH347N ┆   ┆           ┆ your old  ┆           ┆ batch_00 │
│ n8OW      ┆           ┆ Ordinance ┆ n8OW      ┆   ┆           ┆ black     ┆           ┆ 001.parq │
│           ┆           ┆           ┆           ┆   ┆           ┆ dress     ┆           ┆ uet      │
│           ┆           ┆           ┆           ┆   ┆           ┆ An…       ┆           ┆          │
│ 0J1iFISej ┆ I Shall   ┆ Eddie     ┆ 0J1iFISej ┆ … ┆ ok        ┆ They say  ┆ ok_lrclib ┆ results_ │
│ odqBIy0Q9 ┆ Be        ┆ Vedder    ┆ odqBIy0Q9 ┆   ┆           ┆ everythin ┆           ┆ batch_00 │
│ AS0N      ┆ Released  ┆           ┆ AS0N      ┆   ┆           ┆ g can be  ┆           ┆ 001.parq │
│           ┆           ┆           ┆           ┆   ┆           ┆ rep…      ┆           ┆ uet      │
│ 2FSkBDGsq ┆ Just the  ┆ Boyce     ┆ 2FSkBDGsq ┆ … ┆ ok        ┆ Oh her    ┆ ok_lrclib ┆ results_ │
│ ZIxcsnKNg ┆ Way You   ┆ Avenue    ┆ ZIxcsnKNg ┆   ┆           ┆ eyes, her ┆           ┆ batch_00 │
│ tMLx      ┆ Are       ┆           ┆ tMLx      ┆   ┆           ┆ eyes      ┆           ┆ 001.parq │
│           ┆           ┆           ┆           ┆   ┆           ┆ Make the… ┆           ┆ uet      │
│ 6nXIYClvJ ┆ Sky's     ┆ Andrew    ┆ 6nXIYClvJ ┆ … ┆ ok        ┆ You never ┆ ok_lrclib ┆ results_ │
│ Afi6ujLiK ┆ Still     ┆ Belle     ┆ Afi6ujLiK ┆   ┆           ┆ see       ┆           ┆ batch_00 │
│ qEq8      ┆ Blue      ┆           ┆ qEq8      ┆   ┆           ┆ clearly,  ┆           ┆ 001.parq │
│           ┆           ┆           ┆           ┆   ┆           ┆ 'til yo…  ┆           ┆ uet      │
│ 0AYG9Acwq ┆ The Woman ┆ Jason     ┆ 0AYG9Acwq ┆ … ┆ ok        ┆ Maybe I   ┆ ok_lrclib ┆ results_ │
│ EeqgAw3Ov ┆ I Love    ┆ Mraz      ┆ EeqgAw3Ov ┆   ┆           ┆ annoy you ┆           ┆ batch_00 │
│ shPC      ┆           ┆           ┆ shPC      ┆   ┆           ┆ with my   ┆           ┆ 001.parq │
│           ┆           ┆           ┆           ┆   ┆           ┆ choi…     ┆           ┆ uet      │
│ 3SUY9IKXc ┆ Ouija     ┆ Harley    ┆ 3SUY9IKXc ┆ … ┆ ok        ┆ Gonna     ┆ ok_lrclib ┆ results_ │
│ U5VN95FOu ┆           ┆ Poe       ┆ U5VN95FOu ┆   ┆           ┆ play a    ┆           ┆ batch_00 │
│ jS6S      ┆           ┆           ┆ jS6S      ┆   ┆           ┆ show at a ┆           ┆ 001.parq │
│           ┆           ┆           ┆           ┆   ┆           ┆ house t…  ┆           ┆ uet      │
│ 6VtoP2sJt ┆ Someone   ┆ Boyce     ┆ 6VtoP2sJt ┆ … ┆ ok        ┆ I heard   ┆ ok_lrclib ┆ results_ │
│ 5oCmPOQIv ┆ Like You  ┆ Avenue    ┆ 5oCmPOQIv ┆   ┆           ┆ that      ┆           ┆ batch_00 │
│ e2sf      ┆           ┆           ┆ e2sf      ┆   ┆           ┆ you're    ┆           ┆ 001.parq │
│           ┆           ┆           ┆           ┆   ┆           ┆ settled   ┆           ┆ uet      │
│           ┆           ┆           ┆           ┆   ┆           ┆ do…       ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [5]:
EXPECTED_BASE_COLS = [
    'track_id', 'original_name', 'original_artist',
    'metadata_status', 'lyrics', 'lyrics_status'
]

if results_df.is_empty():
    print('No loaded rows to inspect yet.')
else:
    missing = [c for c in EXPECTED_BASE_COLS if c not in results_df.columns]
    if missing:
        print('Missing expected extractor-v8 columns:', missing)
    else:
        print('Extractor-v8 base columns found.')

    if 'track_id' in results_df.columns:
        unique_tracks = results_df.select(pl.col('track_id').cast(pl.Utf8).n_unique()).item()
        duplicates = results_df.height - unique_tracks
        print(f'Unique track_id: {unique_tracks:,}')
        print(f'Duplicate rows by track_id: {duplicates:,}')

    if 'lyrics_status' in results_df.columns:
        status_counts = (
            results_df
            .with_columns(pl.col('lyrics_status').cast(pl.Utf8).fill_null('null').alias('lyrics_status'))
            .group_by('lyrics_status')
            .len()
            .sort('len', descending=True)
        )
        display(status_counts)

        print('\nFull status_counts (no truncation):')
        print('lyrics_status | len')
        print('-' * 80)
        for row in status_counts.iter_rows(named=True):
            print(f"{row['lyrics_status']} | {row['len']}")

        ok_count = results_df.filter(pl.col('lyrics_status').cast(pl.Utf8).str.contains('ok', literal=True)).height
        not_found_only = results_df.filter(
            pl.col('lyrics_status').cast(pl.Utf8).str.contains('not_found', literal=True)
            & ~pl.col('lyrics_status').cast(pl.Utf8).str.contains('ok', literal=True)
        ).height
        print(f'\n\nTotal "ok" count (including variants): {ok_count:,}')
        print(f'Total "not_found" count (without ok fallback): {not_found_only:,}')

Extractor-v8 base columns found.
Unique track_id: 411,000
Duplicate rows by track_id: 0

shape: (54, 2)
┌─────────────────────────────────┬────────┐
│ lyrics_status                   ┆ len    │
│ ---                             ┆ ---    │
│ str                             ┆ u32    │
╞═════════════════════════════════╪════════╡
│ ok_lrclib                       ┆ 257585 │
│ not_found_lrclib->error_librel… ┆ 51142  │
│ not_found_lrclib->error_librel… ┆ 38557  │
│ not_found_lrclib->error_librel… ┆ 21991  │
│ instrumental_lrclib->error_lib… ┆ 10203  │
│ …                               ┆ …      │
│ not_found_lrclib->error_librel… ┆ 1      │
│ http_400_lrclib->error_librely… ┆ 1      │
│ not_found_lrclib->error_librel… ┆ 1      │
│ http_400_lrclib->error_librely… ┆ 1      │
│ http_400_lrclib->ok_librelyric… ┆ 1      │
└─────────────────────────────────┴────────┘

Full status_counts (no truncation):
lyrics_status | len
--------------------------------------------------------------------------------
ok_lrclib | 257585
not_found_lrclib->error_librelyrics: LyricsNotFound->bot_block_genius->not_found_synced | 51142
not_found_lrclib->error_librelyrics: LyricsNotFound->not_found_genius->not_found_synced | 38557
not_found_lrclib->error_librelyrics: LyricsNotFound->ok_genius | 21991
instrumental_lrclib->error_librelyrics: LyricsNotFound->not_found_genius->not_found_synced | 10203
instrumental_lrclib->error_librelyrics: LyricsNotFound->bot_block_genius->not_found_synced | 7178
not_found_lrclib->error_librelyrics: LyricsNotFound->bot_block_genius->ok_synced | 5697
not_found_lrclib->ok_librelyrics | 3793
instrumental_lrclib->error_librelyrics: LyricsNotFound->ok_genius | 3269
not_found_lrclib->skipped_no_auth->ok_genius | 3202
not_found_lrclib->skipped_no_auth->not_found_genius->not_found_synced | 2486
not_found_lrclib->error_librelyrics: LyricsNotFound->not_found_genius->ok_synced | 2421
not_found_lrclib->error_librelyrics: NotValidSp_Dc->bot_block_genius->not_found_synced | 867
not_found_lrclib->error_librelyrics: NotValidSp_Dc->ok_genius | 485
instrumental_lrclib->skipped_no_auth->not_found_genius->not_found_synced | 470
not_found_lrclib->error_librelyrics: NotValidSp_Dc->not_found_genius->not_found_synced | 451
instrumental_lrclib->skipped_no_auth->ok_genius | 231
instrumental_lrclib->error_librelyrics: NotValidSp_Dc->bot_block_genius->not_found_synced | 181
not_found_lrclib->skipped_no_auth->not_found_genius->ok_synced | 136
instrumental_lrclib->ok_librelyrics | 111
instrumental_lrclib->error_librelyrics: LyricsNotFound->not_found_genius->ok_synced | 111
instrumental_lrclib->error_librelyrics: LyricsNotFound->bot_block_genius->ok_synced | 110
not_found_lrclib->error_librelyrics: NotValidSp_Dc->bot_block_genius->ok_synced | 62
http_400_lrclib->error_librelyrics: LyricsNotFound->not_found_genius->not_found_synced | 44
http_400_lrclib->error_librelyrics: LyricsNotFound->bot_block_genius->not_found_synced | 42
not_found_lrclib->skipped_no_auth->bot_block_genius->not_found_synced | 33
instrumental_lrclib->error_librelyrics: NotValidSp_Dc->ok_genius | 32
instrumental_lrclib->error_librelyrics: NotValidSp_Dc->not_found_genius->not_found_synced | 21
not_found_lrclib->error_librelyrics: ProviderError->bot_block_genius->not_found_synced | 15
not_found_lrclib->error_librelyrics: NotValidSp_Dc->not_found_genius->ok_synced | 14
http_400_lrclib->error_librelyrics: LyricsNotFound->ok_genius | 8
not_found_lrclib->error_librelyrics: ProviderError->not_found_genius->not_found_synced | 8
instrumental_lrclib->skipped_no_auth->bot_block_genius->not_found_synced | 7
not_found_lrclib->error_librelyrics: ProviderError->ok_genius | 7
instrumental_lrclib->error_librelyrics: ProviderError->bot_block_genius->not_found_synced | 3
not_found_lrclib->error_librelyrics: LyricsNotFound->not_found_genius->empty_synced | 2
not_found_lrclib->error_librelyrics: LyricsNotFound->error_genius->not_found_synced | 2
instrumental_lrclib->error_librelyrics: LyricsNotFound->error_genius->not_found_synced | 2
instrumental_lrclib->error_librelyrics: NotValidSp_Dc->bot_block_genius->ok_synced | 2
instrumental_lrclib->skipped_no_auth->not_found_genius->ok_synced | 2
http_400_lrclib->skipped_no_auth->not_found_genius->not_found_synced | 2
not_found_lrclib->error_librelyrics: AttributeError->not_found_genius->not_found_synced | 2
http_400_lrclib->skipped_no_auth->ok_genius | 2
not_found_lrclib->error_librelyrics: TOTPGenerationException->not_found_genius->not_found_synced | 1
http_400_lrclib->error_librelyrics: NotValidSp_Dc->not_found_genius->not_found_synced | 1
not_found_lrclib->error_librelyrics: AttributeError->bot_block_genius->not_found_synced | 1
not_found_lrclib->error_librelyrics: AttributeError->ok_genius | 1
not_found_lrclib->skipped_no_auth->bot_block_genius->ok_synced | 1
instrumental_lrclib->error_librelyrics: ProviderError->ok_genius | 1
not_found_lrclib->error_librelyrics: LyricsNotFound->error_genius->ok_synced | 1
http_400_lrclib->error_librelyrics: LyricsNotFound->not_found_genius->ok_synced | 1
not_found_lrclib->error_librelyrics: ProviderError->bot_block_genius->ok_synced | 1
http_400_lrclib->error_librelyrics: LyricsNotFound->bot_block_genius->ok_synced | 1
http_400_lrclib->ok_librelyrics | 1


Total "ok" count (including variants): 299,279
Total "not_found" count (without ok fallback): 111,721

In [6]:
# Quick check of the latest written checkpoint
if checkpoint_files:
    latest_file = checkpoint_files[-1]
    latest_df = read_checkpoint(latest_file)
    print(f'Latest file: {latest_file.name}')
    print(f'Rows in latest file: {latest_df.height:,}')
    print(f'Cols in latest file: {latest_df.width}')
    display(latest_df.head(10))

    if 'lyrics_status' in latest_df.columns:
        latest_status = latest_df.group_by('lyrics_status').len().sort('len', descending=True)
        display(latest_status)
else:
    print('No checkpoint files found.')

Latest file: results_batch_00411.parquet
Rows in latest file: 1,000
Cols in latest file: 19

shape: (10, 19)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ track_id  ┆ original_ ┆ original_ ┆ id        ┆ … ┆ release_d ┆ metadata_ ┆ lyrics    ┆ lyrics_s │
│ ---       ┆ name      ┆ artist    ┆ ---       ┆   ┆ ate       ┆ status    ┆ ---       ┆ tatus    │
│ str       ┆ ---       ┆ ---       ┆ str       ┆   ┆ ---       ┆ ---       ┆ str       ┆ ---      │
│           ┆ str       ┆ str       ┆           ┆   ┆ str       ┆ str       ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 3HCw9YPoN ┆ Más Que   ┆ Jessy J   ┆ 3HCw9YPoN ┆ … ┆ 2008-03-0 ┆ ok        ┆ Mas que   ┆ ok_lrcli │
│ xyFdjDNW4 ┆ Nada      ┆           ┆ xyFdjDNW4 ┆   ┆ 4         ┆           ┆ nada      ┆ b        │
│ PNpU      ┆           ┆           ┆ PNpU      ┆   ┆           ┆           ┆ Sai da    ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ minha     ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ fren…     ┆          │
│ 2FIEhpjfQ ┆ Pennant   ┆ Little    ┆ 2FIEhpjfQ ┆ … ┆ 2021-07-2 ┆ ok        ┆ null      ┆ not_foun │
│ FHn2Tjl5u ┆           ┆ Symphony  ┆ FHn2Tjl5u ┆   ┆ 3         ┆           ┆           ┆ d_lrclib │
│ bfV0      ┆           ┆           ┆ bfV0      ┆   ┆           ┆           ┆           ┆ ->error_ │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ librel…  │
│ 472ybTitt ┆ Wet Mulch ┆ Equipment ┆ 472ybTitt ┆ … ┆ 2019-10-2 ┆ ok        ┆ This is   ┆ ok_lrcli │
│ ytWeHFhL8 ┆           ┆           ┆ ytWeHFhL8 ┆   ┆ 5         ┆           ┆ the one   ┆ b        │
│ hsR6      ┆           ┆           ┆ hsR6      ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ No more   ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ slack…    ┆          │
│ 47xaObKJy ┆ Fallen    ┆ Wormrot   ┆ 47xaObKJy ┆ … ┆ 2016-10-1 ┆ ok        ┆ Yeah!     ┆ ok_lrcli │
│ JPGncrgz4 ┆ Into      ┆           ┆ JPGncrgz4 ┆   ┆ 4         ┆           ┆           ┆ b        │
│ Fo6M      ┆ Disuse    ┆           ┆ Fo6M      ┆   ┆           ┆           ┆ Clouded   ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ by        ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ reality   ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Horr…     ┆          │
│ 7at9R8GFW ┆ Dark      ┆ Great     ┆ 7at9R8GFW ┆ … ┆ 2019-10-2 ┆ ok        ┆ Dark      ┆ ok_lrcli │
│ tbh4dgSOF ┆ Green     ┆ Grandpa   ┆ tbh4dgSOF ┆   ┆ 5         ┆           ┆ Green     ┆ b        │
│ L1Sr      ┆ Water     ┆           ┆ L1Sr      ┆   ┆           ┆           ┆ Water     ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ All       ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ things    ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ fa…       ┆          │
│ 4vil6lFUW ┆ Happy     ┆ Korpiklaa ┆ 4vil6lFUW ┆ … ┆ 2006-01-0 ┆ ok        ┆ He sees   ┆ ok_lrcli │
│ mKimuuK0t ┆ Little    ┆ ni        ┆ mKimuuK0t ┆   ┆ 1         ┆           ┆ himself   ┆ b        │
│ DxFP      ┆ Boozer    ┆           ┆ DxFP      ┆   ┆           ┆           ┆ as the    ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ saviour…  ┆          │
│ 0jBuuIk56 ┆ Óxido     ┆ Foyone    ┆ 0jBuuIk56 ┆ … ┆ 2017-10-1 ┆ ok        ┆ ¿Quién no ┆ ok_lrcli │
│ HoAjiI4JP ┆           ┆           ┆ HoAjiI4JP ┆   ┆ 7         ┆           ┆ tiene     ┆ b        │
│ Kza2      ┆           ┆           ┆ Kza2      ┆   ┆           ┆           ┆ páramos   ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ voland…   ┆          │
│ 5yf3b2Wad ┆ Company   ┆ Limoblaze ┆ 5yf3b2Wad ┆ … ┆ 2022-10-2 ┆ ok        ┆ Legend,   ┆ ok_lrcli │
│ bYwDpLitA ┆           ┆           ┆ bYwDpLitA ┆   ┆ 8         ┆           ┆ oh        ┆ b        │
│ A5SF      ┆           ┆           ┆ A5SF      ┆   ┆           ┆           ┆ Oh        ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Yeah,     ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ yeah      ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ You …     ┆          │
│ 1v463EOwp ┆ 13 Years  ┆ Black     ┆ 1v463EOwp ┆ … ┆ 2018-09-2 ┆ ok        ┆ You're so ┆ ok_lrcli │
│ MhZGo9gKA ┆ Of Grief  ┆ Label     ┆ MhZGo9gKA ┆   ┆ 1         ┆           ┆ fuckin'   ┆ b        │
│ iUlp      ┆           ┆ Society   ┆ iUlp      ┆   ┆           ┆           ┆ tough, so ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ mo…       ┆          │
│ 7dhvQzp0p ┆ The Eyes  ┆ Panchiko  ┆ 7dhvQzp0p ┆ … ┆ 2000-12-0 ┆ ok        ┆ Take me   ┆ ok_lrcli │
│ V7vGMOAkM ┆ of Ibad_R ┆           ┆ V7vGMOAkM ┆   ┆ 5         ┆           ┆ to where  ┆ b        │
│ gxCm      ┆ >O>T      ┆           ┆ gxCm      ┆   ┆           ┆           ┆ they have ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ dun…      ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

shape: (9, 2)
┌─────────────────────────────────┬─────┐
│ lyrics_status                   ┆ len │
│ ---                             ┆ --- │
│ str                             ┆ u32 │
╞═════════════════════════════════╪═════╡
│ ok_lrclib                       ┆ 664 │
│ not_found_lrclib->error_librel… ┆ 134 │
│ not_found_lrclib->error_librel… ┆ 112 │
│ instrumental_lrclib->error_lib… ┆ 40  │
│ instrumental_lrclib->error_lib… ┆ 24  │
│ not_found_lrclib->error_librel… ┆ 14  │
│ not_found_lrclib->error_librel… ┆ 7   │
│ not_found_lrclib->ok_librelyri… ┆ 4   │
│ instrumental_lrclib->error_lib… ┆ 1   │
└─────────────────────────────────┴─────┘

In [7]:
# Optional live monitor: set rounds > 1 to auto-refresh
rounds = 1           # e.g. 20
sleep_seconds = 10   # e.g. 10

for i in range(1, rounds + 1):
    files_now = list_checkpoint_files()
    latest_name = files_now[-1].name if files_now else 'none'
    print(f'[{i}/{rounds}] files={len(files_now)} latest={latest_name}')

    if i < rounds:
        time.sleep(sleep_seconds)

[1/1] files=411 latest=results_batch_00411.parquet